version: "3.7"

services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      # - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data

  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/data/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  # golang:
  #   image: "golang:1.14.3"
  #   ports:
  #     - 3000
  #   working_dir: /data
  #   tty: true
  #   volumes:
  #     - .:/data
